### ISSUE TITLE
Absolute paths

### ISSUE THREAD

**Issue by fpinzn** [Janpot/gulp-htmlbuild#8]
Just a heads up: It won't build the js or css files if the paths in the html start with /. Is a silent error.

**Comment by Janpot** [comment]
@fpinzn I updated the example to take absolute paths into account. https://github.com/Janpot/gulp-htmlbuild/commit/03ccf3eb2cab6276404b68f561ea1f28456509c9#diff-591894ff59dd9161c83a3c03af6130aaR40
Unfortunately this won't work until https://github.com/wearefractal/glob-stream/issues/37 is resolved.
